spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory_db?allowPublicKeyRetrieval=true&useSSL=false
    username: user
    password: user_password
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
