spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product_db
    username: user
    password: user_password
    driver-class-name: org.postgresql.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
